### ISSUE TITLE
Adaptación y Responsive de la página "Egresados"

### ISSUE THREAD

**Issue by MelanieLopAl** [cetav-ddw/lalibertad-cetav#130]
-Asegurarse que en la section "Conoce a nuestros egresad@s" se muestre primero el titulo seguido de la  imagen; 

![Image](https://github.com/cetav-ddw/lalibertad-cetav/assets/107006490/7017b84d-1b14-425a-97eb-ec8bbef7b244)

-Verificar que los testimonios se muestren uno sobre otro: 

![Image](https://github.com/cetav-ddw/lalibertad-cetav/assets/107006490/4231b26b-5683-462e-b9d3-bebf02908a53)

-Verificar que en la section "Nuestros Egresados por Técnico" la lista al darle click a los filtros se vea en dos filas con dos columas de cinco personas cada una: 

![Image](https://github.com/cetav-ddw/lalibertad-cetav/assets/107006490/78c13c19-7280-4254-9606-b67d05dd0a02)

-Asegurarse de que los anuarios se vean uno sobre otro: 

![Image](https://github.com/cetav-ddw/lalibertad-cetav/assets/107006490/d88dfbe1-2729-49f5-ae40-d13a93b96932)

**Comment by larace** [comment]
Ya esta pagina desde un principio era responsive.
